apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/managing/docker-registry

patches:
  - target:
      kind: Deployment
      name: docker-registry
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: PersistentVolumeClaim
      name: docker-registry-pvc
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 50Gi
